@namespace
class SpriteKind:
    Environment = SpriteKind.create()
# This is decided by the players first choice. As the player presses B (has chosen the cave route), it triggers this if conditional. The text dialogue continues, describing the players choice, sprites and offers the next set of choices. 

def on_b_pressed():
    global A, B
    # As the variable B is set at 0, it will only start from this position at the start of the game, after the player has chosen B for their first choice. 
    if B == 0:
        Cave.set_image(assets.image("""
            myImage
        """))
        Cave.set_position(80, 40)
        Tree.set_image(img("""
            ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
        """))
        adventure.clear_text_log()
        # By decreasing A & B variables by one, it stops the other if conditional from being run. The negative numbers indicate that the player has first chosen B and sets up the further set of choices. 
        A += -1
        B += -1
        # The dialogue continues for the cave choice. 
        adventure.add_to_textlog("You've chosen the Cave!")
        pause(1500)
        adventure.clear_text_log()
        adventure.add_to_textlog("Entering into the cave you see most of the light receding behind you.")
        pause(3000)
        adventure.clear_text_log()
        # Moves the sprites to correlate with the next choice (the lower and upper path) 
        Tree.set_position(75, 40)
        Cave.set_position(80, 45)
        Cave.set_image(assets.image("""
            myImage1
        """))
        Tree.set_image(assets.image("""
            myImage
        """))
        adventure.add_to_textlog("After what feels like hours of walking in the dark you reach a broad open space. ")
        pause(3000)
        adventure.clear_text_log()
        adventure.add_to_textlog("You see the path split into two, an upper and a lower path.")
        pause(2500)
        adventure.clear_text_log()
        adventure.add_to_textlog("Which will you choose?")
        pause(3000)
        adventure.clear_text_log()
        adventure.add_to_textlog("Upper (A)     Lower (B)")
        pause(2000)
        adventure.clear_text_log()
    # Making use of the global variable, the next time the player presses B the game will check if the player has chosen A initially. Because B=1, it means they have chosen A initially this is the next subsequent choice. 
    # A(first choice) -> B(second choice) 
    if B == 1:
        B += 1
        adventure.add_to_textlog("You chose to continue walking alongside the river.")
        pause(2000)
        adventure.clear_text_log()
        adventure.add_to_textlog("As the sun is continues to set, your nerves begin to grow.")
        # This changes the appearance of the sprites, corresponding with the dialogue.
        Tree.set_image(img("""
            . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . 4 . . . . . 
                        . . . . 2 . . . . 4 4 . . . . . 
                        . . . . 2 4 . . 4 5 4 . . . . . 
                        . . . . . 2 4 d 5 5 4 . . . . . 
                        . . . . . 2 5 5 5 5 4 . . . . . 
                        . . . . . . 2 5 5 5 5 4 . . . . 
                        . . . . . . 2 5 4 2 4 4 . . . . 
                        . . . . . . 4 4 . . 2 4 4 . . . 
                        . . . . . 4 4 . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . .
        """))
        Tree.set_position(80, 40)
        pause(2500)
        adventure.clear_text_log()
        adventure.add_to_textlog("You approach a small house that looks run down and abandoned. ")
        pause(2500)
        adventure.clear_text_log()
        adventure.add_to_textlog("You decide your best option is to go inside. ")
        pause(2500)
        # The dialogue informs the player of the two choices and the corresponding buttons. 
        adventure.add_to_textlog("Inside the house you see a mobile phone sitting on a table. ")
        pause(2000)
        adventure.clear_text_log()
        adventure.add_to_textlog("Using the phone you are able to call emergency services for help!")
        pause(2000)
        # This signals the end of the game and creates a splash screen that says the player has won. 
        game.game_over(True)
    # This if conditional checks if the global variable B is a negative, which would mean that the player has chosen B for their first choice. After pressing B the dialogue continues leading to a winning ending. 
    # 
    # B(first choice) -> A(second choice)
    if B == -1:
        adventure.clear_text_log()
        Tree.set_image(img("""
            . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . .
        """))
        Cave.set_position(80, 40)
        adventure.add_to_textlog("You chose the lower path.")
        pause(2500)
        adventure.clear_text_log()
        # The sprites continue to change to correspond with the dialogue. 
        Cave.set_image(img("""
            . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . 4 4 . . . . . . . 
                        . . . . . . 4 5 5 4 . . . . . . 
                        . . . . . . 2 5 5 2 . . . . . . 
                        . . . . . . . 2 2 . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . .
        """))
        adventure.add_to_textlog("Eventually, you see a light at the end of the cave")
        pause(2000)
        adventure.clear_text_log()
        Cave.set_image(img("""
            . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . 4 . . . . . 
                        . . . . 2 . . . . 4 4 . . . . . 
                        . . . . 2 4 . . 4 5 4 . . . . . 
                        . . . . . 2 4 d 5 5 4 . . . . . 
                        . . . . . 2 5 5 5 5 4 . . . . . 
                        . . . . . . 2 5 5 5 5 4 . . . . 
                        . . . . . . 2 5 4 2 4 4 . . . . 
                        . . . . . . 4 4 . . 2 4 4 . . . 
                        . . . . . 4 4 . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . .
        """))
        adventure.add_to_textlog("The area looks familiar.")
        pause(1500)
        adventure.clear_text_log()
        Cave.set_image(assets.image("""
            myImage4
        """))
        adventure.add_to_textlog("You realise the light is coming from a nearby carpark, a street lamp.")
        pause(3000)
        adventure.clear_text_log()
        adventure.add_to_textlog("You realise this is the start of the trail, leading back to where you began with your friends ")
        pause(3500)
        adventure.clear_text_log()
        adventure.add_to_textlog("You see them waiting for you in the distance. You are saved!!")
        pause(1500)
        # This signals the end of the game and creates a splash screen that says the player has won. 
        game.game_over(True)
controller.B.on_event(ControllerButtonEvent.PRESSED, on_b_pressed)

# This is decided by the players first choice. As the player presses A (has chosen the tree route), it triggers this if conditional. The text dialogue continues, describing the players choice, sprites and offers the next set of choices. 

def on_a_pressed():
    global A, B
    # As the variable A is set at 0, it will only start from this position at the start of the game, after the player has chosen A for their first choice. 
    if A == 0:
        # Hides the cave image, as the player has chosen the tree route. 
        Cave.set_image(img("""
            ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
        """))
        # By increasing A & B variables by one, it stops the other if conditional from being run. The positive numbers indicate that the player has first chosen A and sets up the further set of choices. 
        A += 1
        B += 1
        Tree.set_position(80, 40)
        # Sets the tree to the main sprite.
        Tree.set_image(img("""
            ........................
                        8..........ff..........8
                        68........f88f........86
                        688......ff88ff......886
                        668......f8888f......866
                        6668....f888888f....8666
                        666688ff88888888ff886666
                        666666888888888888666666
                        666668888888888888866666
                        666666888888888888666666
                        66888668f88888ff86688666
                        8668688888fff88f88886688
                        8868668f8ff8ff8f88686886
                        8888868fff88ffff86688866
                        88888888ff8fffff86888868
                        888668888ffffff888866888
                        68886668ffff8fff86668888
                        6868866688f88f8866688686
                        6866666688888f8666666666
                        666666666888886686666666
                        666666668688888866666666
                        666666666888888666666666
                        6866668666888f8866866686
                        6886866886688f8688668886
                        866888688888f86688688686
                        8866888868ff866886886688
                        88868688668f888866866888
                        88888668868ff88888888888
                        68868868688f888666886688
                        668666666688886668866688
                        666666666668866666666686
                        666668666888888666866666
                        666666888888888888668666
                        6668868ff88f888ff8688668
                        8668888ff8fff88fff888688
                        e88......ffeeff......88e
                        eef......feeeef......fee
                        eef......feeeef......fee
                        feef....feeefeef....feee
                        ffef....fefeffef....fefe
        """))
        # The dialogue continues for the first choice, 
        adventure.add_to_textlog("You've chosen the tree!")
        pause(1500)
        adventure.clear_text_log()
        adventure.add_to_textlog("You make your way between the two tree clearings. ")
        pause(2000)
        adventure.clear_text_log()
        adventure.add_to_textlog("After what feels like hours of walking you approach a river. ")
        Tree.set_image(img("""
            ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
        """))
        # Sets the scene to being a river, as the dialogue changes the sprite coincides. 
        River.set_image(assets.image("""
            myImage3
        """))
        pause(2000)
        adventure.clear_text_log()
        adventure.add_to_textlog("You can either try to cross the river, or continue walking aside it. ")
        pause(2500)
        adventure.clear_text_log()
        # The dialogue informs the player of the two choices and the corresponding buttons. 
        adventure.add_to_textlog("Cross (A)   Continue (B)")
        pause(2500)
        adventure.clear_text_log()
    # Making use of the global variable, the next time the player presses A the game will check if the player has chosen A initially. Because A=1, it means they have chosen A a second time, which leads to a losing ending. A(first choice) -> A(second choice) 
    if A == 1:
        adventure.clear_text_log()
        Tree.set_position(80, 40)
        # This hides the cave as the player has made another choice. 
        Cave.set_image(img("""
            ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
        """))
        adventure.add_to_textlog("You chose to cross the river")
        pause(2000)
        adventure.clear_text_log()
        adventure.add_to_textlog("There is a strong current pulling you downstream")
        pause(2000)
        adventure.clear_text_log()
        # Setting the sprite to a skull to indicate the player has lost. 
        River.set_image(img("""
            ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
        """))
        adventure.add_to_textlog("You exhaust yourself fighting the current and drown!!")
        pause(3000)
        Tree.set_image(assets.image("""
            myImages.image0
        """))
        adventure.clear_text_log()
        # This signals the end of the game and creates a splash screen that says the player has lost. 
        game.game_over(False)
    # This if conditional checks if the global variable A is a negative, which would mean that the player has chosen B for their first choice. After pressing A this dialogue appears and shows a losing ending. 
    # 
    # B(first choice) -> A(second choice)
    if A == -1:
        adventure.clear_text_log()
        Tree.set_position(80, 40)
        # This hides the cave as the player has made another choice. 
        Cave.set_image(img("""
            ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
        """))
        adventure.add_to_textlog("You chose the upper path.")
        pause(2000)
        adventure.clear_text_log()
        adventure.add_to_textlog("After walking you notice rocks slowly falling around you.")
        pause(2000)
        adventure.clear_text_log()
        adventure.add_to_textlog("You continue walking, your nerves heightening.")
        pause(3000)
        adventure.clear_text_log()
        adventure.add_to_textlog("A giant stalactite falls down from the ceiling, impaling you!")
        Tree.set_image(assets.image("""
            myImages.image0
        """))
        pause(3000)
        adventure.clear_text_log()
        # This signals the end of the game and creates a splash screen that says the player has lost. 
        game.game_over(False)
controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)

Cave: Sprite = None
River: Sprite = None
Tree: Sprite = None
B = 0
A = 0
# Beginning of introduction, setting the background colour for the rest of the game 
scene.set_background_color(11)
# Creating global variable A to signify the player choosing A initially and sets it to 0 to show that no choice has been made yet. 
A = 0
# Creating global variable B to signify the player choosing A initially and sets it to 0 to show that no choice has been made yet. 
B = 0
# The first introductory text, adding a sentence of text to the text log that scrolls from the bottom of screen
adventure.add_to_textlog("Welcome to Page Play! A choose your adventure video game with challenging decisions and surprising endings. ")
# Pauses to allow time for each dialogue to appear and to be read 
pause(2000)
# Clears text log to remove old dialogue and create space for the next line of text 
adventure.clear_text_log()
adventure.add_to_textlog("You can interact with this game using 'A' and 'B' to decide between two options. Restart to try different endings! ")
pause(2000)
adventure.clear_text_log()
# Creates a splash screen that signifies the start of the game, waiting for players to press A to begin 
game.splash("Your adventure awaits...")
# Creates the first sprite for option A (tree path), that will later be changed. The kind is set to environment to describe that it will act as a sprite for each option. 
Tree = sprites.create(img("""
        ...................................................................
            ...................................................................
            ...................................................................
            ...................................................................
            ...................................................................
            ...................................................................
            ...................................................................
            ...................................................................
            ...................................................................
            ...................................................................
            ...................................77df............................
            .................................7757eeff..........................
            ................................777777eef..........................
            ...............................7757777eef..........................
            ...............................777757deeeef........................
            ..............................777777effefeef.......................
            ..............................7ffffefffffeeff......................
            ..............................ff..ef4ff............................
            ..................................7e4fffff.........................
            ..................................7e47cfff.........................
            ................................7eee4eeeeef........................
            ................................5777eedeeef.......75...............
            ..............................77777577eeefff.....7e7...............
            ............................777777777777eeef....757efd.............
            ...........................77757777777eeeeecf..7777def.............
            ..........................7777e77e577d7eeeeefff.757e7ef............
            .................77d......7577eeefff77e7eeeefff.7fffeff............
            .................75e......7eeeeffeff775efffeeff...ffffb............
            ................75eefd....fffeffeeefffe7effeeeff..4ff..............
            ................75fcfd......bfcceefeffeeeffffff..74f...............
            ................ffff..........d75eef4effffff.4...777e..............
            .................75f.........7777eef4ef.ffeffff.7777ee.............
            .................7def......757777cee4ef.75eeeffce7eedef............
            ................777ee.....77777deefeeef777edeeffeeffeeef...........
            ...............75efee.....7775eeeeffeeff7d7eeeef7fffffef...........
            ..............775efeee...7777efeeef77ee7777eeeeef7ffdffeed.........
            .............7577fffef..5777dcfeeefb7775e777eeeef54fcf.f...........
            .............74eff4fff..577dfffeeff.6ce7eeeeeeff7777fdc............
            ..............fff.7ef....7efbdeef...4feeceeeeeeff777eef............
            .................77ef...............4fffcdefffff57eedeefd..........
            ................757eeecd..........d.4cf.ffeff.fffeffeeeef..........
            ..............5777deeeef.........5fd4ff.cbff4.7eff4fffeeeff........
            .............577eeeffeeff........77e4ff.....f75eefff5cffeeef.......
            ...........77777eeefffeeff......77ee4ff....f777ee777777ffefff......
            ..........77eeeeeeffeeffff......777f4ff...747eed75777e7eed.........
            ..........5feeeeeec77eee.......574ef4ff..75ecefe77ede77eefc........
            ............f777747eede7fc.....777ef4ff..74ffffeefdeedeeefc........
            ............775774e7eee7ff......75ef4ff..ff.4f.fffeeee7ecfff.......
            ............7777eeeeefeeeef...77ee4e4ffc....4f...feeffeedcf........
            ...........7577eefeeefffeef..57ee77d4fff....ef...feffffffff........
            ...........77eeeeffee...ff...77ff7ee4ffff...7f....fff....fff.......
            ..........777eeffffff........7cc7def4ffff..f77ef..4fee....fff......
            ..........57efff.4f...........5774ef4ff...77eeef..4fef.............
            ...........fff...4f.....7e...547eecf4fff.7eedeef..4ff..............
            ...............7.4f.....eef...bfeecf4fff.77eeeef..4ff..............
            ...............dd4f....77ef...efffff4ffff57effeefd4ff..............
            .................4f....7ecf......ef.4fff.74fffffc.4fff.............
            .................4f....deff......4f.4ff.....4f....4ff..............
            .................4f......c.......4f.4ff.....4f....4fff.............
            .................4f.....ec.......4f.4ff.....4f....4ffff............
            .................4f......e.......4f.4ff.....4f....fff..............
            .................4f......4.......4f.4ff.....4f....fff..............
            .................4f......b.......4f64ff....d4f....fff..............
            ............676664f667666786676664f64ff667664f6667eff886...........
            .........666666664f866666668666664f64ff666664f66664e886866.d.......
            ......6766676667688886676667886764f74ff7666748876667888888676......
            .......666666666668888866666668664f64ff6666688886666688688866......
            .....766676667666766888867666766888cfff867666788886667688788876....
            .....6666666666666666688866666666888688886666668888866668886888....
            ..66666766676667666766688887666766888888888766676888866766886688...
            .......6666666666666666688886666666888888888666666668886666886668..
            ....676667666766676667666766876667668886678888666766.888876.6886.7.
            ................6666..6.....86....6...88.66668866666..6688.....88..
            ...7......67.......7.......7...........8.......8...7.6.7.....6.7.88
            .................................................8.................
            ...................................................................
            ...................................................................
            ...................................................................
            ...................................................................
            ...................................................................
            ...................................................................
            ...................................................................
            ...................................................................
            ...................................................................
            ...................................................................
    """),
    SpriteKind.Environment)
# Creates the first sprite for option B (cave path), that will later be changed. The kind is set to environment to describe that it will act as a sprite for each option. 
River = sprites.create(img("""
        . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . .
    """),
    SpriteKind.Environment)
# Set the sprites position to the middle of the screen, as it is a small sprite that will change its appearance for each consequential choice.
Tree.set_position(80, 35)
# The river is a large background sprite that needs to cover the entire screen, therefore its X and Y position is very low to appear in the bottom right corner. 
River.set_position(7, 0)
Tree.set_stay_in_screen(True)
adventure.add_to_textlog("You awaken in an open forest clearing, unsure how you ended up there. ")
pause(2500)
adventure.clear_text_log()
adventure.add_to_textlog("You panic. Realising you had earlier been on a hike with your friends, which are now nowhere to be found. The sun is now almost set.")
pause(4000)
adventure.clear_text_log()
# The first change in sprite appearance as the dialogue change, the sprite changes to match. 
Tree.set_image(img("""
    ........................
        8..........ff..........8
        68........f88f........86
        688......ff88ff......886
        668......f8888f......866
        6668....f888888f....8666
        666688ff88888888ff886666
        666666888888888888666666
        666668888888888888866666
        666666888888888888666666
        66888668f88888ff86688666
        8668688888fff88f88886688
        8868668f8ff8ff8f88686886
        8888868fff88ffff86688866
        88888888ff8fffff86888868
        888668888ffffff888866888
        68886668ffff8fff86668888
        6868866688f88f8866688686
        6866666688888f8666666666
        666666666888886686666666
        666666668688888866666666
        666666666888888666666666
        6866668666888f8866866686
        6886866886688f8688668886
        866888688888f86688688686
        8866888868ff866886886688
        88868688668f888866866888
        88888668868ff88888888888
        68868868688f888666886688
        668666666688886668866688
        666666666668866666666686
        666668666888888666866666
        666666888888888888668666
        6668868ff88f888ff8688668
        8668888ff8fff88fff888688
        e88......ffeeff......88e
        eef......feeeef......fee
        eef......feeeef......fee
        feef....feeefeef....feee
        ffef....fefeffef....fefe
"""))
# Moves the sprite to an appropriate place to be seen 
Tree.set_position(60, 40)
# Changing the appearance of the cave to show the two options, as the player makes the first decision 
Cave = sprites.create(assets.image("""
    myImage
"""), SpriteKind.Environment)
Cave.set_position(105, 40)
adventure.add_to_textlog("In your surroundings you see a clearing between two trees, or a cave opening.")
pause(2000)
adventure.clear_text_log()
adventure.add_to_textlog("Which will you choose?")
pause(1000)
adventure.clear_text_log()
# The dialogue informs the player of the two choices and the corresponding buttons. 
adventure.add_to_textlog("Tree (A)       Cave (B)")
pause(2000)
adventure.clear_text_log()